[profile.default]
  src = 'contracts'
  out = 'out'
  libs = ['node_modules', 'lib']
  test = 'test/foundry'
  cache_path  = 'cache_forge'
  # auto_detect_solc = false
  # solc = "0.8.23"
  build_info = true
  extra_output = ["storageLayout"]
  fs_permissions = [
    { access = "read", path = "./out"}
  ]

[rpc_endpoints]
  goerli = "https://eth-goerli.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
  mainnet = "https://eth-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
  sepolia = "https://eth-sepolia.g.alchemy.com/v2/${API_KEY_ALCHEMY}"