[profile.default]
  # auto_detect_solc = false
  block_timestamp = 1_680_220_800 # March 31, 2023 at 00:00 GMT
  build_info = true
  bytecode_hash = "none"
  cache_path  = 'cache_forge'
  evm_version = "paris" # See https://www.evmdiff.com/features?name=PUSH0&kind=opcode
  extra_output = ["storageLayout"]
  fs_permissions = [
    { access = "read", path = "./out"}
  ]
  fuzz = { runs = 2048 }
  invariant = { fail_on_revert = true, runs = 512 }
  libs = ['node_modules', 'lib']
  optimizer = true
  optimizer_runs = 200
  out = 'out'
  src = 'contracts'
  test = 'test/foundry'
  # solc = "0.8.23"
  script = "script"

[profile.ci]
  fuzz = { runs = 10_000 }
  verbosity = 4

[etherscan]
  arbitrum = { key = "${API_KEY_ARBISCAN}" }
  avalanche = { key = "${API_KEY_SNOWTRACE}" }
  bnb_smart_chain = { key = "${API_KEY_BSCSCAN}" }
  gnosis_chain = { key = "${API_KEY_GNOSISSCAN}" }
  goerli = { key = "${API_KEY_ETHERSCAN}" }
  mainnet = { key = "${API_KEY_ETHERSCAN}" }
  optimism = { key = "${API_KEY_OPTIMISTIC_ETHERSCAN}" }
  polygon = { key = "${API_KEY_POLYGONSCAN}" }
  sepolia = { key = "${API_KEY_ETHERSCAN}" }

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[rpc_endpoints]
  goerli = "https://eth-goerli.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
  mainnet = "https://eth-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
  sepolia = "https://eth-sepolia.g.alchemy.com/v2/${API_KEY_ALCHEMY}"