name: "CI"

env:
  DOTENV_CONFIG_PATH: "./.env.example"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"

      - name: "Install Pnpm"
        uses: "pnpm/action-setup@v2"
        with:
          version: "8"

      - name: "Install Node.js"
        uses: "actions/setup-node@v3"
        with:
          cache: "pnpm"
          node-version: "lts/*"

      - name: "Install the dependencies"
        run: "pnpm install"
      
      - name: get test data file
        env:
          TOKEN: ${{ secrets.PRIVATE_ACCESS_TOKEN }}
        run: |
          curl -H "Authorization: token ${TOKEN}" https://raw.githubusercontent.com/santteegt/private-test-files/main/pgsplit.csv

      - name: "Lint the code"
        run: "pnpm lint"

      - name: "Add lint summary"
        run: |
          echo "## Lint results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

      - name: "Compile the contracts and generate the TypeChain bindings"
        run: "pnpm typechain"

      - name: "Test the contracts and generate the coverage report"
        run: "pnpm coverage"

      - name: "Add test summary"
        run: |
          echo "## Test results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
